#!/bin/bash

sudo -v

# Keep-alive: update existing `sudo` time stamp until `.osx` has finished.
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

# Make sure we’re using the latest Homebrew
brew update

# Upgrade any already-installed formulae
brew upgrade

brew install autojump
brew install caskroom/cask/brew-cask
brew install docker
brew install fish
brew install git
brew install jq
brew install rbenv
brew install ruby-build
brew install the_silver_searcher
brew install tree
brew install weechat --with-python --with-ruby --with-lua --with-perl
brew install wget
brew install xz

brew cask install alfred
brew cask alfred link
brew cask install amazon-music 
brew cask install dropbox 
brew cask install firefox 
brew cask install google-chrome 
brew cask install iterm2 
brew cask install macvim 
brew cask install mumble
brew cask install screenflow
brew cask install the-unarchiver
brew cask install virtualbox
brew cask install vagrant 
brew cask install vmware-fusion

# cleanup unneeded files
brew cleanup
brew cask cleanup
